const Analysis = require('../models/Analysis');
const Resume = require('../models/Resume');

const exportAnalysis = async (req, res) => {
  try {
    const analysisData = req.body;

    // Generate HTML report
    const html = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="UTF-8">
          <title>Resume Analysis Report</title>
          <style>
            body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; color: #333; }
            h1 { color: #6C5CE7; border-bottom: 3px solid #6C5CE7; padding-bottom: 10px; }
            h2 { color: #5A4FCF; margin-top: 30px; }
            .score { font-size: 48px; font-weight: bold; color: #00B894; }
            .summary { background: #F8F9FA; padding: 20px; border-radius: 8px; margin: 20px 0; }
            .skills { display: flex; flex-wrap: wrap; gap: 10px; margin: 15px 0; }
            .skill-badge { background: #6C5CE7; color: white; padding: 8px 15px; border-radius: 20px; font-size: 14px; }
            .keyword { background: #FF7675; color: white; padding: 6px 12px; border-radius: 15px; font-size: 12px; display: inline-block; margin: 5px; }
            .suggestion { background: #FFF4E6; padding: 15px; margin: 10px 0; border-left: 4px solid #FDCB6E; border-radius: 4px; }
            .strength { color: #00B894; padding: 8px 0; }
            .weakness { color: #E17055; padding: 8px 0; }
            .report-date { color: #636E72; font-size: 14px; margin-bottom: 20px; }
          </style>
        </head>
        <body>
          <h1>📊 Resume Analysis Report</h1>
          <div class="report-date">Generated: ${new Date().toLocaleDateString()}</div>
          
          <div class="summary">
            <h2>ATS Compatibility Score</h2>
            <div class="score">${analysisData.atsScore}%</div>
            <p>Your resume's Applicant Tracking System compatibility score.</p>
          </div>

          <h2>Candidate Summary</h2>
          <p>${analysisData.summary}</p>

          <h2>Key Skills Identified</h2>
          <div class="skills">
            ${analysisData.skills.map(skill => `<span class="skill-badge">${skill}</span>`).join('')}
          </div>

          ${analysisData.missingKeywords.length > 0 ? `
          <h2>Missing Keywords</h2>
          <div>${analysisData.missingKeywords.map(keyword => `<span class="keyword">${keyword}</span>`).join('')}</div>
          ` : ''}

          ${analysisData.suggestions.length > 0 ? `
          <h2>Improvement Suggestions</h2>
          ${analysisData.suggestions.map((suggestion, idx) => 
            `<div class="suggestion"><strong>${idx + 1}.</strong> ${suggestion}</div>`
          ).join('')}
          ` : ''}

          ${analysisData.strengths && analysisData.strengths.length > 0 ? `
          <h2>Strengths</h2>
          ${analysisData.strengths.map(strength => `<div class="strength">✓ ${strength}</div>`).join('')}
          ` : ''}

          ${analysisData.weaknesses && analysisData.weaknesses.length > 0 ? `
          <h2>Areas for Improvement</h2>
          ${analysisData.weaknesses.map(weakness => `<div class="weakness">⚠ ${weakness}</div>`).join('')}
          ` : ''}

          <div style="margin-top: 50px; padding-top: 20px; border-top: 2px solid #DDD; text-align: center; color: #636E72;">
            <p>Generated by AI Resume Analyzer • Powered by Gemini AI</p>
          </div>
        </body>
      </html>
    `;

    // Send HTML as response (browser can print to PDF)
    res.setHeader('Content-Type', 'text/html');
    res.send(html);
  } catch (error) {
    console.error('Error exporting analysis:', error);
    res.status(500).json({ error: 'Failed to export analysis: ' + error.message });
  }
};

module.exports = { exportAnalysis };

